version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "daily"
  - package-ecosystem: pip
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: daily
    groups:
      python-packages:
        patterns:
          - "*"
